# Set nginx base image
FROM nginx

MAINTAINER Adrián García Espinosa "age.apps.dev@gmail.com"

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf


EXPOSE 80
